import { afterEach, describe, expect, test } from "bun:test";
import { mkdtemp, mkdir, rm, stat, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { chunkNotionText, createLifeOSStore, FilesystemStore, normalizeNotionBlock, NotionStore, notionParagraphChildren, NOTION_API_VERSION, resolveStorageConfig } from "./index.ts";

const dirs: string[] = []; afterEach(async () => Promise.all(dirs.splice(0).map((d) => rm(d, { recursive: true, force: true }))));
describe("storage providers", () => {
  test("filesystem is the credential-free default", () => { const c = resolveStorageConfig({ env: {} }); expect(c.provider).toBe("filesystem"); expect(createLifeOSStore(c)).toBeInstanceOf(FilesystemStore); });
  test("filesystem preserves markdown document behavior", async () => { const root = await mkdtemp(join(tmpdir(), "lifeos-store-")); dirs.push(root); await mkdir(join(root, "TELOS")); await writeFile(join(root, "TELOS/MISSION.md"), "mission"); const store = new FilesystemStore({ userDir: root }); expect((await store.getDocument("mission"))?.content).toBe("mission"); });
  test("filesystem exposes provider-neutral document revision metadata", async () => { const root = await mkdtemp(join(tmpdir(), "lifeos-store-")); dirs.push(root); await mkdir(join(root, "TELOS")); await writeFile(join(root, "TELOS/MISSION.md"), "mission"); const revision = await new FilesystemStore({ userDir: root }).getDocumentRevision("mission"); expect(revision?.revision).toHaveLength(64); expect(revision?.updatedAt).toBeTruthy(); });
  test("writing_style follows the upstream principal schema", async () => { const root = await mkdtemp(join(tmpdir(), "lifeos-store-")); dirs.push(root); await mkdir(join(root, "PRINCIPAL")); await writeFile(join(root, "PRINCIPAL/WRITINGSTYLE.md"), "voice"); expect((await new FilesystemStore({ userDir: root }).getDocument("writing_style"))?.content).toBe("voice"); });
  test("single-file collections can never become directories", async () => { const root = await mkdtemp(join(tmpdir(), "lifeos-store-")); dirs.push(root); await mkdir(join(root, "TELOS")); await writeFile(join(root, "TELOS/GOALS.md"), "goals"); const store = new FilesystemStore({ userDir: root }); await expect(store.createRecord("goals", { content: "bad", properties: {} })).rejects.toThrow("single Markdown"); expect((await stat(join(root, "TELOS/GOALS.md"))).isFile()).toBe(true); });
  test("notion fails closed without a token", () => expect(() => resolveStorageConfig({ provider: "notion", env: {} })).toThrow("NOTION_API_KEY"));
  test("resolves logical TOML-style mappings and environment placeholders", () => { const c = resolveStorageConfig({ env: { NOTION_API_KEY: "fixture", ROOT: "root-id" }, config: { storage: { provider: "notion" }, notion: { root_page_id: "${ROOT}", documents: { mission: "mission-id" } } } }); expect(c.notion?.rootPageId).toBe("root-id"); expect(c.notion?.documents.mission).toBe("mission-id"); });
  test("normalizes blocks", () => expect(normalizeNotionBlock({ type: "heading_2", heading_2: { rich_text: [{ plain_text: "Aim" }] } })).toBe("## Aim"));
  test("chunks >2k, >4k, and Unicode content losslessly", () => { for (const text of ["a".repeat(2001), "b".repeat(4001), "🧭".repeat(2500) + "終"]) { const chunks = chunkNotionText(text); expect(chunks.join("")).toBe(text); expect(chunks.every((chunk) => Array.from(chunk).length <= 2000)).toBe(true); const blocks = notionParagraphChildren(text); expect(blocks.map((block: any) => block.paragraph.rich_text[0].text.content).join("")).toBe(text); } });
  test("paginates and recursively retrieves children", async () => {
    const calls: string[] = []; const fake = async (url: any, init: any = {}) => { calls.push(String(url)); const path = String(url);
      if (path.includes("/pages/page")) return new Response(JSON.stringify({ id: "page", properties: {} }), { status: 200 });
      const cursor = path.includes("start_cursor=next");
      return new Response(JSON.stringify(cursor ? { results: [{ id: "two", type: "paragraph", paragraph: { rich_text: [{ plain_text: "world" }] }, has_children: false }], has_more: false } : { results: [{ id: "one", type: "paragraph", paragraph: { rich_text: [{ plain_text: "hello" }] }, has_children: false }], has_more: true, next_cursor: "next" }), { status: 200 });
    };
    const store = new NotionStore({ apiKey: "fixture-token", documents: { mission: "page" }, collections: {}, timeoutMs: 100, maxRetries: 0 }, fake as any);
    expect((await store.getDocument("mission"))?.content).toBe("hello\n\nworld"); expect(calls.length).toBe(3); expect(calls[2]).toContain("start_cursor=next");
  });
  test("sanitizes remote errors and never includes token/body", async () => { const store = new NotionStore({ apiKey: "super-secret-fixture", documents: { mission: "page" }, collections: {}, timeoutMs: 100, maxRetries: 0 }, (async () => new Response("super-secret-fixture backend detail", { status: 401 })) as any); await expect(store.getDocument("mission")).rejects.toThrow("HTTP 401"); try { await store.getDocument("mission"); } catch (e: any) { expect(e.message).not.toContain("super-secret"); } });
  test("uses current data-source query and create semantics", async () => { const calls: Array<{ url: string; init: any }> = []; const fake = async (url: any, init: any = {}) => { calls.push({ url: String(url), init }); return new Response(JSON.stringify(String(url).endsWith("/pages") ? { id: "new", parent: { data_source_id: "source" }, properties: {} } : { results: [], has_more: false }), { status: 200 }); }; const store = new NotionStore({ apiKey: "x", documents: {}, collections: { goals: "source" }, timeoutMs: 100, maxRetries: 0 }, fake as any); await store.queryCollection("goals", { limit: 2 }); await store.createRecord("goals", { properties: {}, content: "x" }); expect(calls[0].url).toContain("/data_sources/source/query"); expect(calls[0].init.headers["Notion-Version"]).toBe(NOTION_API_VERSION); expect(JSON.parse(calls[1].init.body).parent).toEqual({ type: "data_source_id", data_source_id: "source" }); });
  test("authorizes records only by configured data_source_id", async () => { const fake = async () => new Response(JSON.stringify({ id: "record", parent: { data_source_id: "other-source" }, properties: {} }), { status: 200 }); const store = new NotionStore({ apiKey: "x", documents: {}, collections: { goals: "source" }, timeoutMs: 100, maxRetries: 0 }, fake as any); await expect(store.getRecord("goals", "record")).rejects.toThrow("outside configured goals data source"); });
  test("hydrates only bounded selected record bodies", async () => { const calls: string[] = []; const fake = async (url: any) => { const path = String(url); calls.push(path); if (path.includes("/data_sources/")) return new Response(JSON.stringify({ results: [{ id: "one", properties: {} }, { id: "two", properties: {} }], has_more: true, next_cursor: "more" }), { status: 200 }); return new Response(JSON.stringify({ results: [{ id: "block", type: "paragraph", paragraph: { rich_text: [{ plain_text: path.includes("one") ? "first" : "second" }] } }], has_more: false }), { status: 200 }); }; const store = new NotionStore({ apiKey: "x", documents: {}, collections: { goals: "source" }, timeoutMs: 100, maxRetries: 0 }, fake as any); const records = await store.queryCollection("goals", { limit: 1, hydrateContent: true }); expect(records).toHaveLength(1); expect(records[0].content).toBe("first"); expect(calls.filter((call) => call.includes("/children"))).toHaveLength(1); });
  test("rejects body replacement before sending any request", async () => { let calls = 0; const store = new NotionStore({ apiKey: "x", documents: {}, collections: { goals: "source" }, timeoutMs: 100, maxRetries: 0 }, (async () => { calls++; return new Response("{}"); }) as any); await expect(store.updateRecord("goals", "record", { content: "replacement" })).rejects.toThrow("replacement is unsupported"); expect(calls).toBe(0); });
  test("managed hot-memory replacement preserves unmanaged blocks and selects newest generation", async () => {
    let revision = "r1"; let sequence = 0; let failCleanup = true; const blocks: any[] = [{ id: "human", type: "paragraph", paragraph: { rich_text: [{ plain_text: "human content" }] } }];
    const fake = async (url: any, init: any = {}) => { const path = String(url);
      if (path.endsWith("/pages/memory")) return new Response(JSON.stringify({ id: "memory", last_edited_time: revision, properties: {} }));
      if (path.endsWith("/blocks/memory/children") && (!init.method || init.method === "GET")) return new Response(JSON.stringify({ results: blocks, has_more: false }));
      if (path.endsWith("/blocks/memory/children") && init.method === "PATCH") { for (const child of JSON.parse(init.body).children) { sequence++; blocks.push({ ...child, id: `owned-${sequence}`, [child.type]: { ...child[child.type], rich_text: child[child.type].rich_text.map((item: any) => ({ ...item, plain_text: item.text.content })) } }); } revision = `r${sequence + 1}`; return new Response(JSON.stringify({})); }
      if (init.method === "DELETE") { if (failCleanup) { failCleanup = false; return new Response("cleanup failed", { status: 500 }); } const id = decodeURIComponent(path.split("/").pop()!); const at = blocks.findIndex((block) => block.id === id); if (at >= 0) blocks.splice(at, 1); return new Response(JSON.stringify({})); }
      throw new Error(`unexpected ${init.method ?? "GET"} ${path}`);
    };
    const store = new NotionStore({ apiKey: "x", documents: { principal_memory: "memory" }, collections: {}, timeoutMs: 100, maxRetries: 0 }, fake as any);
    await expect(store.replaceDocument("principal_memory", "first")).rejects.toThrow("explicit managed initialization");
    await store.initializeManagedDocument("principal_memory"); const expectedRevision = (await store.getDocumentRevision("principal_memory"))!.revision;
    await expect(store.replaceDocument("principal_memory", "new 🧭 memory", { expectedRevision })).rejects.toThrow("HTTP 500");
    expect((await store.getDocument("principal_memory"))?.content).toBe("new 🧭 memory"); expect(blocks.some((block) => block.id === "human")).toBe(true);
    await expect(store.replaceDocument("principal_memory", "stale", { expectedRevision })).rejects.toThrow("changed since it was read");
    await expect(store.replaceDocument("mission", "nope")).rejects.toThrow("non-managed");
  });
  test("honors Retry-After and retries bounded transient failures", async () => { let n = 0; const delays: number[] = []; const store = new NotionStore({ apiKey: "x", rootPageId: "root", documents: {}, collections: {}, timeoutMs: 100, maxRetries: 1 }, (async () => { n++; return new Response(JSON.stringify({ id: "root" }), { status: n === 1 ? 429 : 200, headers: n === 1 ? { "Retry-After": "2" } : {} }); }) as any, async (ms) => { delays.push(ms); }); expect((await store.healthCheck()).ok).toBe(true); expect(n).toBe(2); expect(delays).toEqual([2000]); });
  test("times out with a sanitized error", async () => { const store = new NotionStore({ apiKey: "x", documents: { mission: "page" }, collections: {}, timeoutMs: 5, maxRetries: 0 }, ((_: any, init: any) => new Promise((_, reject) => init.signal.addEventListener("abort", () => reject(Object.assign(new Error(), { name: "AbortError" }))))) as any); await expect(store.getDocument("mission")).rejects.toThrow("Notion request failed"); });
});
